### PR TITLE
changed some file names

### PR DESCRIPTION
**Pull request by antter**
I just changed filenames so they are saved under a folder of the repo / user which you are planning to predict

### CODE REVIEW

**Comment by MichaelClifford** [comment]
@aakankshaduggal can you help out with the merge conflicts in this PR?

**Comment by aakankshaduggal** [comment]
> @aakankshaduggal can you help out with the merge conflicts in this PR?

Sure :+1:

**Comment by antter** [comment]
filenames were changed in another PR

**Pull request closed without merging**
