### PR TITLE
fixed some bugs for functionality in elyra pipeline

### PR DESCRIPTION
**Pull request by antter**
had to make some changes so pipeline works smoothly

### CODE REVIEW

**Comment by MichaelClifford** [comment]
@harshad16 why has the build-check not recorded the reason for failure?

image

**Comment by harshad16** [comment]
>why has the build-check not recorded the reason for failure?

because the logs are lost after 3hours
we don't have resources to store this and show them
`/retest` can be used to retrigger.

**Comment by MichaelClifford** [comment]
@harshad16 the error is:

```
Running Python version 3.6, but Pipfile.lock requires Python version 3.8
subprocess exited with status 3
subprocess exited with status 3
error building at STEP "RUN /opt/app-root/builder/assemble": exit status 3'
+ exit_code=3
+ set -e
+ [[ 3 -ne 0 ]]
+ state=failure
+ desc='The image build test failed!'
```

How do we ensure the CI uses the right version of python. All the configuration files in the repo (.thoth, .prow, .aicoe-ci) seem to reference only  python 3.8

**Comment by harshad16** [comment]
> the error is:
> 
> ```
> Running Python version 3.6, but Pipfile.lock requires Python version 3.8
> subprocess exited with status 3
> subprocess exited with status 3
> error building at STEP "RUN /opt/app-root/builder/assemble": exit status 3'
> + exit_code=3
> + set -e
> + [[ 3 -ne 0 ]]
> + state=failure
> + desc='The image build test failed!'
> ```
> 
> How do we ensure the CI uses the right version of python. All the configuration files in the repo (.thoth, .prow, .aicoe-ci) seem to reference only python 3.8

@MichaelClifford  please change the base image: https://github.com/aicoe-aiops/github-labeler/blob/023e57ade107be63efc7048ffdd83e5d720ab9cf/.aicoe-ci.yaml#L10
to either `s2i-custom-py38-notebook` 
and if you want elyra pre-installed then use `s2i-elyra-custom-notebook`

**Comment by MichaelClifford** [comment]
@antter can you include @harshad16 's suggested change above into this PR?

**Comment by antter** [comment]
> @antter can you include @harshad16 's suggested change above into this PR?

Yea, I was changing around the Pipfile and aicoe-ci.yaml stuff today, going to check that everything with the updated version works then open a different PR with that, then rebase so this works too.

**Pull request merged**
